apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-app-
spec:
  entrypoint: deploy
  templates:
  - name: deploy
    steps:
    - - name: update-image
        template: update-image

  - name: update-image
    container:
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - |
          kubectl set image deployment/your-deployment-name your-container-name=${IMAGE_TAG}
      env:
      - name: IMAGE_TAG
        value: "{{workflow.parameters.image-tag}}"
