apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: secret
    repoURL:  https://github.com/sosotechnologies/sosodocker.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true