apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ecr-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    ecr-push:
      port: "12000"
      endpoint: /ecr-push
      method: POST
