apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment-name
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app-name
  template:
    metadata:
      labels:
        app: your-app-name
    spec:
      containers:
      - name: your-container-name
        image: 368085106192.dkr.ecr.us-east-1.amazonaws.com/sosotech:1.0.0 # This will be updated by the GitHub Actions pipeline
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: aws-ecr-secret