apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sosotech
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sosotech
  template:
    metadata:
      labels:
        app: nodejs-sosotech
    spec:
      containers:
      - name: nodejs-sosotech
        image: 368085106192.dkr.ecr.us-east-1.amazonaws.com/sosotech:v0.0.13 
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: ecr-registry-secret
