apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nodejs-sosotech
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nodejs-sosotech
  type: LoadBalancer
status:
  loadBalancer: {}
