#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to AWS ElasticBeanstalk
#---------------------------------------------------------------------
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install AWS CLI
      run: |
        pip install awscli --upgrade --user

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.MY_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.MY_SECRET_ACCESS_KEY }}
        aws configure set region eu-north-1

    # - name: Build and push Docker image
    #     env:
    #       ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    #       IMAGE_TAG: ${{ github.sha }}
    #     run: |
    #       # Build the Docker image
    #       docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

    #       # Tag the Docker image
    #       docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    #       # Push the Docker image to ECR
    #       docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
